runtime: python39
instance_class: F1

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  PYTHONUNBUFFERED: "true"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

handlers:
- url: /.*
  script: auto
  secure: always 